server:
  port: 9001
spring:
  application:
    name: xdclass-user-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/xdclass?useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: Mysql666!!

  redis:
    host: 13.43.86.57
    port: 6378
    password: Mysql666!!

  mail:
    host: smtp.gmail.com
    port: 587
    username: songyi102788@gmail.com
    password: scra zegj bdez njxl
    from: songyi102788@gmail.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    root: info
